RA-11 screen recipes is added
alulcardino/RecipeApp pull request #9
Opened 2023-12-04 20:15 UTC by alulcardino

2023-12-04 20:19 UTC, alulcardino commented
Вопрос насчет размера картинок, просто картинка замыливается при переходе в рецепты. Это так и должно быть или можно исправить?

2023-12-05 14:28 UTC, ievetrov requested changes

2023-12-05 14:28 UTC, ievetrov commented on app/src/main/res/layout/fragment_recipes_list.xml
> +                android:scaleType="fitXY"
давай везде поменяем на centerCrop
это самый распространенный подход к центрированию. картинка не будет искажаться

2023-12-05 14:28 UTC, ievetrov commented on app/src/main/java/com/romanmikhailenko/recipeapp/RecipesListFragment.kt
> +import androidx.core.os.bundleOf
следи за неиспользуемыми импортами. автоформатирование обычно решает эту проблему

2023-12-05 14:28 UTC, ievetrov commented on app/src/main/java/com/romanmikhailenko/recipeapp/RecipesListAdapter.kt
> +                itemClickListener?.onItemClick(dataset.indexOf(currentItem))
индекс далеко не означает реальный айдишник элемента. нам надо обратиться именно к объекту рецепта и считать его свойство

2023-12-05 14:43 UTC, ievetrov commented
> Вопрос насчет размера картинок, просто картинка замыливается при переходе в рецепты. Это так и должно быть или можно исправить?

не заметил сразу. да, так как мы достаем их сырыми и не масштабируемыми они мылятся на высоком разрешении. но позже мы заменим этот способ на загрузку из сети

2023-12-05 14:43 UTC, ievetrov approved these changes

2023-12-05 14:44 UTC, merged